### ISSUE TITLE
macOS High Sierra

### ISSUE THREAD

**Issue by fixflash** [macmade/FileVaultCracker#10]
Hi, it’s me again. 

I tried this app on macOS High Sierra. When I entered the UUID of core storage I got the message that it is not encrypted (it’s true), so I suppose that the app operates well in this OS. 

Then I entered the UUID of my SSD (which is blocked by FileVault and connected to this MacBook via dock station) and got the same  notification as earlier  "UUID is not a valid CoreStorage volume UUID".

So the questions is: How to unblock external (not core) storage?

or

How to make my blocked SSD core storage if I cannot launch OS from it because I forgot this damn FileVault password and restoration  via apple ID doesn’t work? 

All the best

**Comment by macmade** [comment]
Can you post the infos of the SSD drive so I can take a look?

**Comment by fixflash** [comment]
Sure I can
https://ibb.co/P65q6qQ

**Comment by macmade** [comment]
Well, unfortunately it looks like your volume is not a CoreStorage one.
Is it an APFS volume?

Please post the output of:

    diskutil coreStorage list

**Comment by fixflash** [comment]
Probably blocked SSD is an APFS volume. It's mentioned in the info.

CoreStorage logical volume groups **(1 found)** 
|
+-- Logical Volume Group DBD064CC-7C3F-4160-B8B7-9D242DC09C5A
    =========================================================
    Name:         Mac
    Status:       Online
    Size:         999345127424 B (999.3 GB)
    Free Space:   0 B (0 B)
    |
    +-< Physical Volume AD636542-575B-40EF-A174-2805E3BAD72C
    |   ----------------------------------------------------
    |   Index:    0
    |   Disk:     disk0s2
    |   Status:   Online
    |   Size:     999345127424 B (999.3 GB)
    |
    +-> Logical Volume Family 04A9BE3A-8CEE-4B32-BD03-D86A7A11FBFE
        ----------------------------------------------------------
        Encryption Type:         None
        |
        +-> Logical Volume 21BE1D71-DEF3-4FDE-A9D2-C0B96FFD1DD6
            ---------------------------------------------------
            Disk:                  disk1
            Status:                Online
            Size (Total):          998992805888 B (999.0 GB)
            Revertible:            Yes (no decryption required)
            LV Name:               Mac
            Volume Name:           Mac
            Content Hint:          Apple_HFS

But I have 2 volumes connected...

Is it possible to convert blocked APFS volume to HFS+?

**Comment by macmade** [comment]
Right, your SSD is APFS, so not using CoreStorage and technically not using FileVault, as APFS encryption is a completely different story.

So I’m afraid this software won’t be able to help you.

**Comment by macmade** [comment]
And of course you cannot convert an encrypted volume.

**Comment by fixflash** [comment]
Would you recommend some software to decrypt APFS?

**Comment by macmade** [comment]
Unfortunately I don’t know any. Maybe check with Apple if they can help you with the AppleID recovery, or if you have set a recovery key in iCloud.

**Comment by fixflash** [comment]
Ok, thanks, I'll try, but last time Apple said that they didn't provide more support for MacBook 2011.

**Comment by macmade** [comment]
Good luck
