### ISSUE TITLE
High Sierra 10.13 Beta 3 FileVault locked hard drive and only 60% complete

### ISSUE THREAD

**Issue by markstachowski** [macmade/FileVaultCracker#2]
Please help...  I have a 2014 MacBook Pro with 1TB SSD.  I installed High Sierra 10.13 beta 3 and FileVault ran then froze 60% completed.  I can't log into my Hard drive now and the password causes a kernel panic, then reboot loop each time.  I beg you, please help.

Marks-iMac:/ root# diskutil apfs list
APFS Container (1 found)
|
+-- Container disk1 485B7C24-832B-40BE-B6BB-C869492DB627
    ====================================================
    APFS Container Reference:     disk1
    Capacity Ceiling (Size):      999040462848 B (999.0 GB)
    Capacity In Use By Volumes:   967064211456 B (967.1 GB) (96.8% used)
    Capacity Available:           31976251392 B (32.0 GB) (3.2% free)
    |
    +-< Physical Store disk0s2 51500AD0-2104-4786-B735-E92AE9587207
    |   -----------------------------------------------------------
    |   APFS Physical Store Disk:   disk0s2
    |   Size:                       999040462848 B (999.0 GB)
    |
    +-> Volume disk1s1 728909BE-B86A-3A8B-9748-5D71DC69DA0B
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s1 (No specific role)
    |   Name:                      Macintosh HD (Case-insensitive)
    |   Mount Point:               Not Mounted
    |   Capacity Consumed:         959202942976 B (959.2 GB)
    |   Encryption Progress:       60.0% (Locked)
    |
    +-> Volume disk1s2 5E520A95-D69A-4F6F-84E4-7448E27492E4
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s2 (Preboot)
    |   Name:                      Preboot (Case-insensitive)
    |   Mount Point:               Not Mounted
    |   Capacity Consumed:         4999376896 B (5.0 GB)
    |   Encrypted:                 No
    |
    +-> Volume disk1s3 BBFE1826-2FBF-4E16-8013-4EB7D72098AC
    |   ---------------------------------------------------
    |   APFS Volume Disk (Role):   disk1s3 (Recovery)
    |   Name:                      Recovery (Case-insensitive)
    |   Mount Point:               Not Mounted
    |   Capacity Consumed:         506667008 B (506.7 MB)
    |   Encrypted:                 No
    |
    +-> Volume disk1s4 4E4395FC-8E97-437C-A45A-68A1072E191F
        ---------------------------------------------------
        APFS Volume Disk (Role):   disk1s4 (VM)
        Name:                      VM (Case-insensitive)
        Mount Point:               Not Mounted
        Capacity Consumed:         2147586048 B (2.1 GB)
        Encrypted:                 No
Marks-iMac:/ root#

**Comment by macmade** [comment]
Not sure I can help here, as I'm not really familiar with the FileVault encryption process.

Did you get these logs from the recovery partition?

**Comment by markstachowski** [comment]
I got them from terminal and the command 'diskutil apfs list'.  Would the FileVault cracker help?  I'm not sure?

**Comment by markstachowski** [comment]
I tried almost everything sadly any help would be appreciated.

**Comment by markstachowski** [comment]
Marks-iMac:~ markstachowski$ diskutil apfs listCryptoUsers
No APFS Volume specified
Marks-iMac:~ markstachowski$ diskutil apfs listCryptoUsers 728909BE-B86A-3A8B-9748-5D71DC69DA0B
Cryptographic users (3 found)
|
+-- BE96C522-D309-49F6-AA11-0D4077A3C918
|   Type: Local Open Directory
|
+-- EC1C2AD9-B618-4ED6-BD8D-50F361C27507
|   Type: iCloud
|
+-- 64C0C6EB-0000-11AA-AA11-00306543ECAC
    Type: iCloud Recovery
 
Marks-iMac:~ markstachowski$

**Comment by macmade** [comment]
Honestly, I'm not sure it can help... But you might still give it a try.

I would suggest booting from an external disk.  
Since it looks like your main disk has been converted to APFS, it means the external disk's OS has to be macOS 10.13.  
Otherwise there's no way the disk can mount.

From the external OS, first try mounting the disk as usual.

If it doesn't work, then try FileVault Cracker from the external system.  
As you obviously know your own password, create a word list containing only your password, and run the tool.

Hope you'll recover your hard drive...

**Comment by markstachowski** [comment]
Thank you!  I will try this with an external disk.  How do I install FileVault Cracker?  I don't see a .dmg file or instructions.  I will try anything.

**Comment by macmade** [comment]
You’ll have to build the project. Know how to use Xcode?

**Comment by markstachowski** [comment]
I do, it was installed before my MacBook crashed.  I'll download it over the weekend again and compile/build it with Xcode.  Thank you.  I hope it works, but could be the keychain is corrupted and no passwords will work at all.  This seems to be a common problem with this beta, so you'd be the first person it figure out a solution.  Apple has no clue so far how to fix it.

**Comment by macmade** [comment]
No worries, let me know if this works. 🤞
