### ISSUE TITLE
Best way to connect Air

### ISSUE THREAD

**Issue by bikr** [macmade/FileVaultCracker#3]
Im' trying to recover for a deceased co-worker's relative.  I have a macbook air.  What's the best way to connect and how do I get the UUID of the drive etc?

**Comment by macmade** [comment]
You can use target mode and use Disk Utility or System Info to get the UUID.

**Comment by bikr** [comment]
Great thanks! 
Lastly, does the word list use combos of words? 

I’m pretty sure the pass is either 2 or 3 words and one of a set numbers (dogs names and address number)
