### ISSUE TITLE
AKS Error

### ISSUE THREAD

**Issue by paun93** [macmade/FileVaultCracker#5]
When trying to use your app to mount an encrypted filecracker volume, it keeps giving me this error:
_AKS Error
Could not store a passphrase with ASK. Please start again with fewer threads. Note that you may need to restart your computer._

I've restarted it a few times, even lowered the amount of threads to 1, but every time it goes through maybe 80 passwords in the wordlist, it stops afterwards with this error.

I've tested it with a wordlist of 9 words and it did work (it went through the whole list), but otherwise it keeps giving this error.

I am running a macOS 10.14.1 Mojave on a VMWare workstation, and I'm not quite familiar with macOS. 
If anything is needed additional, just tell me what should I attach and how.

Thank you in advance

**Comment by fishybiss** [comment]
I have the same issue here

**Comment by github-nvo** [comment]
same problem:
run as root - works for me :-)
