### ISSUE TITLE
UUID is not a valid CoreStorage volume UUID

### ISSUE THREAD

**Issue by fixflash** [macmade/FileVaultCracker#9]
Hello,

I entered UUID of SSD which I extracted from my macbook and connected via docking station to another one where I installed FileVaultCracker. After a try to mount I got the notification "UUID is not a valid CoreStorage volume UUID".

If I understood correctly the programm needs UUID of the core storage (where operationing OS is) but unfortunately I can't launch FileVaultCracker on my macbook because it's blocked by FileVault password which I forgot.

I wonder you will recommend some solution because FileVaultCracker is my last hope.

All the best

**Comment by fixflash** [comment]
I also tried the UUID of operationing macbook but I got the same notification and nothing happened.

**Comment by macmade** [comment]
The UUID can be found with DiskUtility, even when booting from another drive or computer.

**Comment by fixflash** [comment]
Yes, I know I entered proper UUID but got notification “UUID is not a valid CoreStorage volume UUID” and then nothing happened.

**Comment by macmade** [comment]
Unfortunately, this software was originally built for macOS 10.12 (Sierra).  
A lot of things has change since then, including APFS.

Due to the nature of this software, I'm not providing support for latest macOS versions.
